eicoop: BaseModal: fix 'Error: Passing props on "template"!'
Currently the modal causes

  Error: Passing props on "template"!

  The current component <TransitionChild /> is rendering a "template".
  However we need to passthrough the following props:
    - ref

Not sure why headlessui is reacting so violently to something that doesn't seem
to have a visible effect, but let's just fix it with an additional level of
div.